[package]
name = "elasticsearch-provider"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
base64 = { workspace = true }
elasticsearch = { workspace = true }
extension-protocol = { workspace = true }
interprocess = { workspace = true, features = ["tokio"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
uuid = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
extension-host = { workspace = true }
tempfile = "3"
