package dbipc

import (
	"encoding/json"
	"fmt"
	"strings"
)

type tableSpec struct {
	Name        string          `json:"name"`
	Schema      string          `json:"schema,omitempty"`
	Database    string          `json:"database,omitempty"`
	Columns     []columnDDL     `json:"columns"`
	PrimaryKey  []string        `json:"primary_key,omitempty"`
	Indexes     []indexDDL      `json:"indexes,omitempty"`
	ForeignKeys []foreignKeyDDL `json:"foreign_keys,omitempty"`
	Comment     string          `json:"comment,omitempty"`
}

type columnDDL struct {
	Name          string  `json:"name"`
	Type          string  `json:"type"`
	Nullable      *bool   `json:"nullable,omitempty"`
	Default       *string `json:"default,omitempty"`
	IsPrimary     bool    `json:"is_primary,omitempty"`
	IsUnique      bool    `json:"is_unique,omitempty"`
	AutoIncrement bool    `json:"auto_increment,omitempty"`
	Comment       string  `json:"comment,omitempty"`
}

type indexDDL struct {
	Name        string   `json:"name"`
	Columns     []string `json:"columns"`
	Kind        string   `json:"kind,omitempty"`
	IsUnique    bool     `json:"is_unique,omitempty"`
	WhereClause string   `json:"where,omitempty"`
}

type foreignKeyDDL struct {
	Name     string   `json:"name"`
	FromCols []string `json:"from_columns"`
	ToTable  string   `json:"to_table"`
	ToCols   []string `json:"to_columns"`
	OnDelete string   `json:"on_delete,omitempty"`
	OnUpdate string   `json:"on_update,omitempty"`
}

type createTableOptions struct {
	IfNotExists     bool  `json:"if_not_exists,omitempty"`
	WithIndexes     *bool `json:"with_indexes,omitempty"`
	WithForeignKeys *bool `json:"with_foreign_keys,omitempty"`
	Temporary       bool  `json:"temporary,omitempty"`
}

type alterTableOptions struct {
	AllowDestructive bool `json:"allow_destructive,omitempty"`
	WithRollback     bool `json:"with_rollback,omitempty"`
}

type columnRenameDDL struct {
	OldName string `json:"old_name"`
	NewName string `json:"new_name"`
}

func buildCreateTableSQL(spec DriverSpec, table tableSpec, options createTableOptions) (string, []string, error) {
	if table.Name == "" {
		return "", nil, fmt.Errorf("missing table name")
	}
	if len(table.Columns) == 0 {
		return "", nil, fmt.Errorf("create table requires at least one column")
	}

	defs := make([]string, 0, len(table.Columns)+len(table.ForeignKeys)+1)
	var inlinePK []string
	for _, column := range table.Columns {
		def, err := buildColumnDefinition(spec, column)
		if err != nil {
			return "", nil, err
		}
		defs = append(defs, def)
		if column.IsPrimary {
			inlinePK = append(inlinePK, column.Name)
		}
	}
	pk := table.PrimaryKey
	if len(pk) == 0 {
		pk = inlinePK
	}
	if len(pk) > 0 {
		defs = append(defs, "PRIMARY KEY ("+quoteIdentifierList(spec, pk)+")")
	}
	if optionDefaultTrue(options.WithForeignKeys) {
		for _, fk := range table.ForeignKeys {
			defs = append(defs, buildForeignKeyDefinition(spec, fk))
		}
	}

	parts := []string{"CREATE"}
	if options.Temporary {
		parts = append(parts, "TEMPORARY")
	}
	parts = append(parts, "TABLE")
	if options.IfNotExists {
		parts = append(parts, "IF NOT EXISTS")
	}
	sqlText := strings.Join(parts, " ") + " " + qualifiedTableName(spec, table.Database, table.Schema, table.Name) + " (" + strings.Join(defs, ", ") + ")"
	statements := []string{sqlText}
	if optionDefaultTrue(options.WithIndexes) {
		for _, idx := range table.Indexes {
			if len(idx.Columns) == 0 {
				continue
			}
			stmt := "CREATE "
			if idx.IsUnique {
				stmt += "UNIQUE "
			}
			stmt += "INDEX " + quoteIdentifier(spec, idx.Name) + " ON " + qualifiedTableName(spec, table.Database, table.Schema, table.Name) + " (" + quoteIdentifierList(spec, idx.Columns) + ")"
			if idx.WhereClause != "" {
				stmt += " WHERE " + idx.WhereClause
			}
			statements = append(statements, stmt)
		}
	}
	return sqlText, statements, nil
}

func buildColumnDefinition(spec DriverSpec, column columnDDL) (string, error) {
	if column.Name == "" {
		return "", fmt.Errorf("column name is required")
	}
	if strings.TrimSpace(column.Type) == "" {
		return "", fmt.Errorf("column %s type is required", column.Name)
	}
	parts := []string{quoteIdentifier(spec, column.Name), column.Type}
	if column.AutoIncrement {
		parts = append(parts, "GENERATED BY DEFAULT AS IDENTITY")
	}
	if column.Nullable != nil && !*column.Nullable {
		parts = append(parts, "NOT NULL")
	}
	if column.Default != nil && strings.TrimSpace(*column.Default) != "" {
		parts = append(parts, "DEFAULT", *column.Default)
	}
	if column.IsUnique && !column.IsPrimary {
		parts = append(parts, "UNIQUE")
	}
	return strings.Join(parts, " "), nil
}

func buildForeignKeyDefinition(spec DriverSpec, fk foreignKeyDDL) string {
	parts := []string{}
	if fk.Name != "" {
		parts = append(parts, "CONSTRAINT", quoteIdentifier(spec, fk.Name))
	}
	parts = append(parts, "FOREIGN KEY", "("+quoteIdentifierList(spec, fk.FromCols)+")", "REFERENCES", quoteIdentifier(spec, fk.ToTable), "("+quoteIdentifierList(spec, fk.ToCols)+")")
	if fk.OnDelete != "" {
		parts = append(parts, "ON DELETE", strings.ToUpper(strings.ReplaceAll(fk.OnDelete, "_", " ")))
	}
	if fk.OnUpdate != "" {
		parts = append(parts, "ON UPDATE", strings.ToUpper(strings.ReplaceAll(fk.OnUpdate, "_", " ")))
	}
	return strings.Join(parts, " ")
}

func buildDropSQL(spec DriverSpec, kind, database, schema, name string, ifExists, cascade bool) (string, error) {
	if name == "" {
		return "", fmt.Errorf("missing object name")
	}
	normalizedKind := strings.ToUpper(strings.TrimSpace(kind))
	switch normalizedKind {
	case "TABLE", "BASE_TABLE":
		normalizedKind = "TABLE"
	case "VIEW":
		normalizedKind = "VIEW"
	case "MATERIALIZED_VIEW":
		normalizedKind = "MATERIALIZED VIEW"
	case "INDEX":
		normalizedKind = "INDEX"
	case "SCHEMA":
		normalizedKind = "SCHEMA"
	case "DATABASE":
		normalizedKind = "DATABASE"
	default:
		return "", fmt.Errorf("unsupported drop kind %q", kind)
	}
	sqlText := "DROP " + normalizedKind
	if ifExists {
		sqlText += " IF EXISTS"
	}
	sqlText += " " + qualifiedTableName(spec, database, schema, name)
	if cascade {
		sqlText += " CASCADE"
	}
	return sqlText, nil
}

func buildAlterTableSQL(spec DriverSpec, fromSpec, toSpec tableSpec, renames []columnRenameDDL, options alterTableOptions) ([]string, []string, []string, error) {
	table := toSpec
	if table.Name == "" {
		table = fromSpec
	}
	if table.Name == "" {
		return nil, nil, nil, fmt.Errorf("alter table requires a table name")
	}
	tableName := qualifiedTableName(spec, table.Database, table.Schema, table.Name)
	var statements []string
	var rollback []string
	var warnings []string

	for _, rename := range renames {
		if rename.OldName == "" || rename.NewName == "" {
			continue
		}
		statements = append(statements, fmt.Sprintf("ALTER TABLE %s RENAME COLUMN %s TO %s", tableName, quoteIdentifier(spec, rename.OldName), quoteIdentifier(spec, rename.NewName)))
		if options.WithRollback {
			rollback = append([]string{fmt.Sprintf("ALTER TABLE %s RENAME COLUMN %s TO %s", tableName, quoteIdentifier(spec, rename.NewName), quoteIdentifier(spec, rename.OldName))}, rollback...)
		}
	}
	fromCols := map[string]columnDDL{}
	for _, c := range fromSpec.Columns {
		fromCols[c.Name] = c
	}
	toCols := map[string]columnDDL{}
	for _, c := range toSpec.Columns {
		toCols[c.Name] = c
		if _, ok := fromCols[c.Name]; !ok {
			def, err := buildColumnDefinition(spec, c)
			if err != nil {
				return nil, nil, nil, err
			}
			statements = append(statements, fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s", tableName, def))
			if options.WithRollback {
				rollback = append([]string{fmt.Sprintf("ALTER TABLE %s DROP COLUMN %s", tableName, quoteIdentifier(spec, c.Name))}, rollback...)
			}
		}
	}
	if options.AllowDestructive {
		for _, c := range fromSpec.Columns {
			if _, ok := toCols[c.Name]; !ok {
				statements = append(statements, fmt.Sprintf("ALTER TABLE %s DROP COLUMN %s", tableName, quoteIdentifier(spec, c.Name)))
				warnings = append(warnings, "drop column may lose data: "+c.Name)
			}
		}
	}
	return statements, rollback, warnings, nil
}

func quoteIdentifier(spec DriverSpec, name string) string {
	left := spec.IdentifierQuoteLeft
	right := spec.IdentifierQuoteRight
	if left == "" && right == "" {
		left = `"`
		right = `"`
	}
	if right == "" {
		right = left
	}
	if left == "" && right == "" {
		return name
	}
	return left + strings.ReplaceAll(name, right, right+right) + right
}

func quoteIdentifierList(spec DriverSpec, names []string) string {
	quoted := make([]string, 0, len(names))
	for _, name := range names {
		if name != "" {
			quoted = append(quoted, quoteIdentifier(spec, name))
		}
	}
	return strings.Join(quoted, ", ")
}

func qualifiedTableName(spec DriverSpec, database, schema, name string) string {
	parts := make([]string, 0, 3)
	for _, part := range []string{database, schema, name} {
		if strings.TrimSpace(part) != "" {
			parts = append(parts, quoteIdentifier(spec, part))
		}
	}
	return strings.Join(parts, ".")
}

func optionDefaultTrue(value *bool) bool {
	return value == nil || *value
}

func decodePayload[T any](raw json.RawMessage, target *T) error {
	return json.Unmarshal(raw, target)
}
