[package]
name = "navop-rdp-helper"
version = "0.3.5"
edition = "2024"
publish = false

[workspace]

[dependencies]
anyhow = "1"
ironrdp = { git = "https://github.com/feigeCode/IronRDP", rev = "149606a4f3d10c94649a81855b8902e65d0c3766", features = [
    "connector",
    "cliprdr",
    "graphics",
    "input",
    "pdu",
] }
ironrdp-client = { git = "https://github.com/feigeCode/IronRDP", rev = "149606a4f3d10c94649a81855b8902e65d0c3766", default-features = false, features = [
    "clipboard",
    "native-tls",
    "sound",
] }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smallvec = "1"
tempfile = "3"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
whoami = "1"
